"""add Social Fields to User model

Revision ID: 0c91d9921daf
Revises: 77c4b4e5e48f
Create Date: 2025-08-29 02:06:21.178271

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c91d9921daf"
down_revision: Union[str, None] = "77c4b4e5e48f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("social_provider", sa.String(), nullable=True))
    op.add_column("user", sa.Column("social_id", sa.String(), nullable=True))
    op.add_column("user", sa.Column("social_image", sa.String(), nullable=True))
    op.create_unique_constraint("unique_social_account", "user", ["social_provider", "social_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_social_account", "user", type_="unique")
    op.drop_column("user", "social_image")
    op.drop_column("user", "social_id")
    op.drop_column("user", "social_provider")
    # ### end Alembic commands ###
