"""add indexes based on foreignkeys

Revision ID: 1181140f14bd
Revises: 78c27e87b824
Create Date: 2025-07-20 03:52:06.470715

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1181140f14bd"
down_revision: Union[str, None] = "78c27e87b824"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("journey_match_id_key"), "journey", type_="unique")
    op.create_index(op.f("ix_journey_match_id"), "journey", ["match_id"], unique=True)
    op.create_index(op.f("ix_match_user1_id"), "match", ["user1_id"], unique=False)
    op.create_index(op.f("ix_match_user2_id"), "match", ["user2_id"], unique=False)
    op.create_index(
        op.f("ix_meeting_feedback_meeting_request_id"),
        "meeting_feedback",
        ["meeting_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_feedback_user_id"), "meeting_feedback", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_meeting_request_journey_id"), "meeting_request", ["journey_id"], unique=False
    )
    op.create_index(op.f("ix_message_journey_id"), "message", ["journey_id"], unique=False)
    op.create_index(op.f("ix_photo_user_id"), "photo", ["user_id"], unique=False)
    op.drop_constraint(op.f("profile_user_id_key"), "profile", type_="unique")
    op.create_index(op.f("ix_profile_user_id"), "profile", ["user_id"], unique=True)
    op.drop_constraint(op.f("questionnaire_user_id_key"), "questionnaire", type_="unique")
    op.create_index(op.f("ix_questionnaire_user_id"), "questionnaire", ["user_id"], unique=True)
    op.create_index(
        op.f("ix_questionnaire_field_category_id"),
        "questionnaire_field",
        ["category_id"],
        unique=False,
    )
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_index(op.f("ix_questionnaire_field_category_id"), table_name="questionnaire_field")
    op.drop_index(op.f("ix_questionnaire_user_id"), table_name="questionnaire")
    op.create_unique_constraint(
        op.f("questionnaire_user_id_key"),
        "questionnaire",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_profile_user_id"), table_name="profile")
    op.create_unique_constraint(
        op.f("profile_user_id_key"), "profile", ["user_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_photo_user_id"), table_name="photo")
    op.drop_index(op.f("ix_message_journey_id"), table_name="message")
    op.drop_index(op.f("ix_meeting_request_journey_id"), table_name="meeting_request")
    op.drop_index(op.f("ix_meeting_feedback_user_id"), table_name="meeting_feedback")
    op.drop_index(op.f("ix_meeting_feedback_meeting_request_id"), table_name="meeting_feedback")
    op.drop_index(op.f("ix_match_user2_id"), table_name="match")
    op.drop_index(op.f("ix_match_user1_id"), table_name="match")
    op.drop_index(op.f("ix_journey_match_id"), table_name="journey")
    op.create_unique_constraint(
        op.f("journey_match_id_key"), "journey", ["match_id"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
