"""add users acceptance fields for Journey

Revision ID: 1c6b10ee2cff
Revises: bbf52b8fce1d
Create Date: 2025-09-20 00:10:02.890572

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c6b10ee2cff"
down_revision: Union[str, None] = "bbf52b8fce1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journey", sa.Column("user1_accepted", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "journey", sa.Column("user2_accepted", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journey", "user2_accepted")
    op.drop_column("journey", "user1_accepted")
    # ### end Alembic commands ###
