"""add acceptance fields to Match

Revision ID: 259d6a453ea9
Revises: f66cdcce4ac2
Create Date: 2025-08-01 18:04:37.155704

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "259d6a453ea9"
down_revision: Union[str, None] = "f66cdcce4ac2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("user1_accepted", sa.Boolean(), nullable=False))
    op.add_column("match", sa.Column("user2_accepted", sa.Boolean(), nullable=False))
    op.add_column("match", sa.Column("matched_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "matched_at")
    op.drop_column("match", "user2_accepted")
    op.drop_column("match", "user1_accepted")
    # ### end Alembic commands ###
