"""add sub-category between Category & Field

Revision ID: 3011ce16e6d2
Revises: 6f80f09e3cd0
Create Date: 2025-08-29 16:08:26.648381

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3011ce16e6d2"
down_revision: Union[str, None] = "6f80f09e3cd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questionnaire_subcategory",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("order_position", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["questionnaire_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_questionnaire_subcategory_category_id"),
        "questionnaire_subcategory",
        ["category_id"],
        unique=False,
    )
    op.add_column("questionnaire_category", sa.Column("image_url", sa.String(), nullable=True))
    op.drop_column("questionnaire_category", "step")
    op.drop_column("questionnaire_category", "picture_url")
    op.add_column("questionnaire_field", sa.Column("sub_category_id", sa.UUID(), nullable=False))
    op.drop_index(op.f("ix_questionnaire_field_category_id"), table_name="questionnaire_field")
    op.create_index(
        op.f("ix_questionnaire_field_sub_category_id"),
        "questionnaire_field",
        ["sub_category_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("questionnaire_field_category_id_fkey"), "questionnaire_field", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "questionnaire_field", "questionnaire_subcategory", ["sub_category_id"], ["id"]
    )
    op.drop_column("questionnaire_field", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questionnaire_field",
        sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "questionnaire_field", type_="foreignkey")
    op.create_foreign_key(
        op.f("questionnaire_field_category_id_fkey"),
        "questionnaire_field",
        "questionnaire_category",
        ["category_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_questionnaire_field_sub_category_id"), table_name="questionnaire_field")
    op.create_index(
        op.f("ix_questionnaire_field_category_id"),
        "questionnaire_field",
        ["category_id"],
        unique=False,
    )
    op.drop_column("questionnaire_field", "sub_category_id")
    op.add_column(
        "questionnaire_category",
        sa.Column("picture_url", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questionnaire_category",
        sa.Column("step", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("questionnaire_category", "image_url")
    op.drop_index(
        op.f("ix_questionnaire_subcategory_category_id"), table_name="questionnaire_subcategory"
    )
    op.drop_table("questionnaire_subcategory")
    # ### end Alembic commands ###
