"""add parent/child field to QuestField

Revision ID: 3869543babf6
Revises: 3011ce16e6d2
Create Date: 2025-08-29 17:49:34.821943

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3869543babf6"
down_revision: Union[str, None] = "3011ce16e6d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questionnaire_field", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_questionnaire_field_parent_id"), "questionnaire_field", ["parent_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "questionnaire_field",
        "questionnaire_field",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("questionnaire_field", "parent_field")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questionnaire_field",
        sa.Column("parent_field", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "questionnaire_field", type_="foreignkey")
    op.drop_index(op.f("ix_questionnaire_field_parent_id"), table_name="questionnaire_field")
    op.drop_column("questionnaire_field", "parent_id")
    # ### end Alembic commands ###
