"""turn SubCategory nullable in Field

Revision ID: 3ca927913fd6
Revises: 3869543babf6
Create Date: 2025-08-29 18:10:18.167915

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ca927913fd6"
down_revision: Union[str, None] = "3869543babf6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questionnaire_field", "sub_category_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questionnaire_field", "sub_category_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
