"""Add user acceptance fields to match model

Revision ID: 3eb4cac67bf8
Revises: f66cdcce4ac2
Create Date: 2025-08-07 12:22:07.792980

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3eb4cac67bf8"
down_revision: Union[str, None] = "f66cdcce4ac2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column("match", sa.Column("user1_accepted", sa.Boolean(), nullable=True))
    op.add_column("match", sa.Column("user2_accepted", sa.Boolean(), nullable=True))

    # Update existing records to have default values
    op.execute("UPDATE match SET user1_accepted = false WHERE user1_accepted IS NULL")
    op.execute("UPDATE match SET user2_accepted = false WHERE user2_accepted IS NULL")

    # Now make them not nullable
    op.alter_column("match", "user1_accepted", nullable=False)
    op.alter_column("match", "user2_accepted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "user2_accepted")
    op.drop_column("match", "user1_accepted")
    # ### end Alembic commands ###
