"""add deleted_at to User

Revision ID: 41032d6262c8
Revises: e03a5e26effb
Create Date: 2025-11-30 07:22:46.193317

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41032d6262c8"
down_revision: Union[str, None] = "e03a5e26effb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deleted_at")
    op.drop_column("user", "deactivated_at")
    # ### end Alembic commands ###
