"""add phone_region to User Model

Revision ID: 77c4b4e5e48f
Revises: c0ffee123456
Create Date: 2025-08-24 01:46:07.539223

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77c4b4e5e48f"
down_revision: Union[str, None] = "c0ffee123456"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("phone_region", sa.String(), nullable=True))
    op.drop_index(op.f("ix_user_phone_number"), table_name="user")
    op.create_index(op.f("ix_user_phone_number"), "user", ["phone_number"], unique=False)
    op.create_unique_constraint("unique_phone_number", "user", ["phone_region", "phone_number"])
    op.create_check_constraint(
        constraint_name="both_number_and_region_or_none",
        table_name="user",
        condition="((phone_region IS NOT NULL AND phone_number IS NOT NULL) OR (phone_region IS NULL AND phone_number IS NULL))",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("both_number_and_region_or_none", "user", type_="check")
    op.drop_constraint("unique_phone_number", "user", type_="unique")
    op.drop_index(op.f("ix_user_phone_number"), table_name="user")
    op.create_index(op.f("ix_user_phone_number"), "user", ["phone_number"], unique=True)
    op.drop_column("user", "phone_region")
    # ### end Alembic commands ###
