"""update user & journey fields

Revision ID: 78c27e87b824
Revises: 7f5623766c63
Create Date: 2025-07-19 18:40:21.616500

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78c27e87b824"
down_revision: Union[str, None] = "7f5623766c63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journey", sa.Column("status", sa.String(), server_default="active", nullable=False)
    )
    op.add_column("journey", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("journey", sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "user",
        sa.Column("is_banned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("user", sa.Column("ban_reason", sa.String(), nullable=True))
    op.add_column("user", sa.Column("banned_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "banned_at")
    op.drop_column("user", "ban_reason")
    op.drop_column("user", "is_banned")
    op.drop_column("journey", "ended_at")
    op.drop_column("journey", "completed_at")
    op.drop_column("journey", "status")
    # ### end Alembic commands ###
