"""add verified_at & is_admin to User

Revision ID: 7f5623766c63
Revises: 6178a23f5fdf
Create Date: 2025-07-18 00:40:33.034027

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f5623766c63"
down_revision: Union[str, None] = "6178a23f5fdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column("user", sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "verified_at")
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
