"""remove device_id

Revision ID: 9af0360333da
Revises: b7746d711e1f
Create Date: 2025-09-20 23:56:42.001403

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9af0360333da"
down_revision: Union[str, None] = "b7746d711e1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_tokens_device_id"), table_name="device_tokens")
    op.drop_column("device_tokens", "device_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device_tokens", sa.Column("device_id", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_index(op.f("ix_device_tokens_device_id"), "device_tokens", ["device_id"], unique=True)
    # ### end Alembic commands ###
