"""remove 2 fields from Form

Revision ID: a2e42da1d5f4
Revises: 46bca2f8da76
Create Date: 2025-09-21 21:47:20.261852

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2e42da1d5f4"
down_revision: Union[str, None] = "46bca2f8da76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questionnaire", "partner_physical_preferences")
    op.drop_column("questionnaire", "children_infos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questionnaire",
        sa.Column("children_infos", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questionnaire",
        sa.Column("partner_physical_preferences", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
