"""add twilio msg_id

Revision ID: a54aac915e02
Revises: a1b2c3d4e5f6
Create Date: 2025-08-16 01:46:00.068919

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a54aac915e02"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("twilio_msg_id", sa.String(), nullable=True))
    op.alter_column("message", "sender_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message", "sender_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("message", "twilio_msg_id")
    # ### end Alembic commands ###
