"""Update user model for firebase auth

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2025-06-21 12:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6g7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add the new columns first
    op.add_column('user', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('user', sa.Column('firebase_uid', sa.String(), nullable=True))
    op.add_column('user', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('platform', sa.String(), nullable=True))
    
    # 2. Create a new phone column
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    
    # 3. Copy data from phone_number to phone
    op.execute('UPDATE "user" SET phone = phone_number')
    
    # 4. Create index on phone column
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    
    # 5. Drop the old phone_number column
    op.drop_index('ix_user_phone_number', table_name='user')
    op.drop_column('user', 'phone_number')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add the phone_number column back
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    
    # 2. Copy data from phone to phone_number
    op.execute('UPDATE "user" SET phone_number = phone')
    
    # 3. Recreate index on phone_number
    op.create_index('ix_user_phone_number', 'user', ['phone_number'], unique=True)
    
    # 4. Drop the new columns
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'platform')
    op.drop_column('user', 'device_id')
    op.drop_column('user', 'firebase_uid')
    op.drop_column('user', 'profile_image')
    
    # ### end Alembic commands ###
