"""fix formfield cols

Revision ID: b9e77c4b418b
Revises: 95da117260dd
Create Date: 2025-07-15 00:50:08.909718

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9e77c4b418b"
down_revision: Union[str, None] = "95da117260dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questionnaire_category", sa.Column("step", sa.Integer(), nullable=False))
    op.alter_column(
        "questionnaire_category",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=False,
    )
    op.create_unique_constraint(None, "questionnaire_category", ["name"])
    op.alter_column("questionnaire_field", "description", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("questionnaire_field", "options")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questionnaire_field", sa.Column("options", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.alter_column("questionnaire_field", "description", existing_type=sa.TEXT(), nullable=True)
    op.drop_constraint(None, "questionnaire_category", type_="unique")
    op.alter_column(
        "questionnaire_category",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("questionnaire_category", "step")
    # ### end Alembic commands ###
