"""add some fields to Questionnaire

Revision ID: bbf52b8fce1d
Revises: 3ca927913fd6
Create Date: 2025-08-29 18:55:06.450373

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbf52b8fce1d"
down_revision: Union[str, None] = "3ca927913fd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questionnaire", sa.Column("partner_physical_preferences", sa.String(), nullable=True)
    )
    op.add_column("questionnaire", sa.Column("children_infos", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questionnaire", "children_infos")
    op.drop_column("questionnaire", "partner_physical_preferences")
    # ### end Alembic commands ###
