"""add deletion_requested_at to User

Revision ID: d2e18e11e6aa
Revises: 41032d6262c8
Create Date: 2025-11-30 15:57:02.290864

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2e18e11e6aa"
down_revision: Union[str, None] = "41032d6262c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deletion_requested_at")
    # ### end Alembic commands ###
