"""add fields to message

Revision ID: e91623dc1b51
Revises: c511520b6df1
Create Date: 2025-07-20 22:58:22.531110

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e91623dc1b51"
down_revision: Union[str, None] = "c511520b6df1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "message",
        sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("message", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "deleted_at")
    op.drop_column("message", "is_deleted")
    op.drop_column("message", "moderated_at")
    # ### end Alembic commands ###
